### ISSUE TITLE
A is B considered harmful

### ISSUE THREAD

**Issue by pfps** [w3c/rch-wg-charter#67]
Saying that “Linked Data” is used as a synonym to “RDF” doesn't make it so but has the connotation that W3C considers it to be so.   Unless W3C actually considers this to be so (and evidence of this is provided) the statement should not be in the WG charter.

**Comment by iherman** [comment]
@pfps, the proposed additional note, in #65 is:

> A terminological note: in what follows in this charter, and in the terminology to be used by the Working Group, the term “Linked Data” is used as a synonym to “RDF”. 

I.e., we do not say that LD is synonymous with RDF in general. It is restricted to the usages of the terms in the context of this specific work. (I agree with you that such a statement should not be done in general.)

**Comment by pfps** [comment]
I don't think that an academic-style qualification is sufficient to prevent the statement from having a general connotation.  I certainly have difficulties here, as I believe that linked data and RDF are different in just about every way and that it was a grave mistake to not have JSON-LD be called JSON-RDF.

**Comment by iherman** [comment]
> it was a grave mistake to not have JSON-LD be called JSON-RDF

I tend to agree with you, @pfps (although I may not qualify as "grave"), but that boat has sailed... And, as I said in the mails, communities use these terms very differently, including some that do not make a difference between LD and RDF :-(

**Comment by gkellogg** [comment]
> I don't think that an academic-style qualification is sufficient to prevent the statement from having a general connotation. I certainly have difficulties here, as I believe that linked data and RDF are different in just about every way and that it was a grave mistake to not have JSON-LD be called JSON-RDF.

The original definition of JSON-LD was "JSON for Linking Data", and was changed to "A JSON-based Serialization for Linked Data". Both are correct, as the intention was to allow JSON to express Linked Data by introducing the ability to use IRIs. But, we became sloppy in our messaging.

I think it's important to keep the distinction between "RDF" the abstract syntax/data model, and "Linked Data" the use pattern for referring to or talking about things on the web. RDF provides a general mechanism for expressing graphs/datasets which can link to other resources on the web. JSON-LD allows JSON to be used for linking to other resources, but is an concrete RDF syntax (it says so in the spec). I'm afraid that this helped start the fuzziness of terminology which has gone on to have a marketing connotation.

I think it's probably bad behavior for W3C to further the conflation of the terminology, and it would be best for the specs that are about data representation and not so much about linking to data on the web, to maintain that distinction.

The fact that RDF has become a term that turns off some communities is unfortunate. We should try to move towards clarity of terminology and say what we mean, not try to massage terminology to satisfy a perceived bias in the target communities and dilute the messaging.

**Comment by gkellogg** [comment]
I think it would be worth distinguishing the terms _Linked Data_ and _RDF_, perhaps by saying that RDF is the data model or Abstract Syntax used for describing Linked Data. While Linked Data is data that is expressed in some RDF concrete syntax, which expresses data on the web. The distinction is that RDF is more like a language and Linked Data is something written in that language (using "language" as an abstract concept, not a serialization format).

Just as JSON-LD can be described as a way to use JSON for expressing Linked Data using the RDF data model, Turtle could be described as "a Terse RDF Triple Language for expressing Linked Data".

**Comment by pchampin** [comment]
closing this issue. It has become moot with the new focus of this charter on RDF C14N. Neither the charter nor the explainer contain the term "linked data" anymore.
