### ISSUE TITLE
Stale expressions of support

### ISSUE THREAD

**Issue by pfps** [w3c/rch-wg-charter#97]
Why are there many expressions of support for a no-longer-really-in-progress charter littering the issue list here?

**Comment by pchampin** [comment]
Thanks for pointing that out.

The `expression_of_support` tag has been replaced with `expression_of_support_OUTDATED` on all issues,
then turned back to `expression_of_support` only when the author explicitly renewed their support, taking in consideration the change of scope and the new version of the charter.
