### ISSUE TITLE
quantifier scoping 

### ISSUE THREAD

**Issue by pfps** [w3c/rch-wg-charter#98]
"This specification defines an algorithm to produce a canonicalization function of an arbitrary RDF Dataset. "

Is this "for any dataset there is a (one?) function for canonicalizing it" or "there is a (one?) function for canonicalizing all datasets"?  The wording seems to lean towards the former but the need is for the latter.

**Comment by aidhog** [comment]
Agreed.

The canonicalization function is defined elsewhere, so would propose to replace with something like:

> This specification defines an algorithm that implements an [RDF Dataset Canonicalization function](https://w3c.github.io/rch-wg-charter/explainer.html#canonicalization).

**Comment by pchampin** [comment]
@pfps, the new version does not contain the "quantification" anymore. We adopted @aidhog's proposal [above](https://github.com/w3c/rch-wg-charter/issues/98#issuecomment-1026382325).

Do you agree to close this issue?
